import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { calculateImport, type ImportOperation } from "@exporta/domain";
import { convertCurrency, type ExchangeRates } from "../src/lib/currency";
import { operationReportData, createOperationPdf, createOperationWorkbook } from "../src/lib/operation-report";
import { buildPortfolioReport, defaultPortfolioReportFilters } from "../src/lib/portfolio-report";
import { portfolioReportData } from "../src/lib/portfolio-report-export";
import { reportDate } from "../src/lib/report-format";
const rates: ExchangeRates = { dollar: { buy: 5, sell: 5, quotedAt: "2026-09-30T13:00:00-03:00", source: "BCB PTAX" }, yuan: { buy: 0.7, sell: 0.75, quotedAt: "2026-09-30T13:00:00-03:00", source: "BCB PTAX" } };
const operation: ImportOperation = { id: "o1", reference: "EB-2026-001", customer: "Importadora Brasil / 中国贸易", assigneeId: "lucas", assigneeName: "Nome antigo", port: "Santos", container: "ABCD1234567", status: "in_transit", portStatus: "in_transit", customsChannel: "green", shipmentStatus: "shipped", eta: "2026-09-29", createdAt: "2026-09-01", updatedAt: "2026-10-01T16:00:00Z", exchangeRate: 4, freightBrl: 99999, insuranceBrl: 99999, portExpensesBrl: 99999, budgets: [{ id: "b1", name: "Custos aprovados", number: 1, status: "approved", createdAt: "2026-09-01", approvedAt: "2026-09-28T12:00:00Z", approvedBy: "lucas", exchangeRate: 6, marginRate: 20, taxRates: [{ code: "pis_import", rate: 2, source: "manual" }, { code: "cofins_import", rate: 8, source: "default" }, { code: "icms_import", rate: 18, source: "manual" }], expenses: [{ id: "e1", label: "Frete internacional", category: "Frete", amount: 100, currency: "USD", allocationMethod: "fob", status: "approved", exchangeRate: 6 }] }], actualExpenses: [{ id: "r1", label: "Armazenagem", category: "Porto", amount: 500, currency: "BRL", allocationMethod: "fob", status: "paid" }], items: Array.from({ length: 35 }, (_, index) => ({ id: `p${index}`, name: `Motor elétrico industrial ${index + 1}`, chineseName: "工业电动机", englishName: "Industrial electric motor", sku: `M-${index}`, description: "Motor elétrico industrial para linha de produção, uso contínuo, potência de 3 kW.", ncm: "85015210", quantity: 10, unitPriceUsd: 10, grossWeightKg: 2, netWeightKg:20, iiRate: 10, ipiRate: 10, boxCount: 2, boxWeightKg: 10, unitsPerBox: 5, totalVolumeM3: 0.5 })), tasks: [{ id: "t1", title: "Conferir documentação aduaneira", assigneeId: "lucas", assignee: "Nome antigo", dueDate: "2026-09-30", completed: false, createdAt: "2026-09-01T12:00:00Z" }], documents: [{ id: "d1", type: "Invoice", title: "Fatura comercial", reference: "INV-001", issuedAt: "2026-09-01", expiresAt: "2026-09-30", status: "available", createdAt: "2026-09-01" }], timeline: Array.from({length:22}, (_, index)=>({id:`m${index}`, title:`Marco ${index + 1}`, description:"Documento recebido e custos revisados pela operação.", actorId:"lucas", actorName:"Nome antigo", occurredAt:"2026-09-29T17:30:00Z", recordedAt:"2026-09-29T17:31:00Z", type:"milestone"})) };
const context = { timeline: operation.timeline!, tasks: operation.tasks!, documents: operation.documents!, rates, users: [{ id: "lucas", name: "Lucas Costa" }] };
test("conversions use BRL per currency, support zero/negative values and never invent rates", () => { assert.equal(convertCurrency(150, "BRL", "CNY", rates), 200); assert.equal(convertCurrency(150, "BRL", "USD", rates), 30); assert.equal(convertCurrency(10, "USD", "CNY", rates), 50 / .75); assert.equal(convertCurrency(0, "BRL", "CNY", rates), 0); assert.equal(convertCurrency(-5, "USD", "BRL", rates), -25); assert.equal(convertCurrency(1, "BRL", "CNY", null), null); assert.equal(convertCurrency(1, "BRL", "USD", {...rates, dollar:{...rates.dollar,sell:0}}), null); assert.equal(reportDate("invalid"), "—"); });
test("operation exports reconcile with active budget, preserve complete data and audit authors", async () => { const data=operationReportData(operation,context), calculated=calculateImport(operation); assert.equal(data.summary.find(row=>row.label==='Despesas estimadas')?.value,600); assert.equal(data.summary.find(row=>row.label==='CUSTO TOTAL PROJETADO')?.value,calculated.totalCost); assert.ok(Math.abs(Number(data.summary.find(row=>row.label==='PIS-importação')?.value)-431.9)<0.001); assert.equal(data.sheets.find(s=>s.name==='Linha do tempo')?.rows.length,22); assert.equal(data.sheets.find(s=>s.name==='Pendências')?.rows[0][1],'Lucas Costa'); assert.equal(data.sheets.find(s=>s.name==='Documentos')?.rows[0][4],'Vencido'); const workbook=createOperationWorkbook(operation,context); const sheet=workbook.getWorksheet('Itens e custos')!; assert.equal(sheet.getCell('B4').value,600); assert.deepEqual(sheet.getCell('B5').value,{formula:"B4/'Cotações e metodologia'!$B$5", result:800}); assert.equal(sheet.getCell('B5').font.size,9); assert.equal(workbook.getWorksheet('Produtos')!.getCell('B4').value,'工业电动机'); });
test("portfolio distinguishes phases and excludes budget-only arrival risks; selected report exports its sections",()=>{ const budget={...operation,id:'o2',budgets:operation.budgets!.map(b=>({...b,status:'draft' as const})),actualExpenses:[],tasks:[],documents:[]}; const filters={...defaultPortfolioReportFilters(),from:'2026-01-01',to:'2026-12-31'};const report=buildPortfolioReport([operation,budget],filters); assert.equal(report.approvedOperations,1);assert.equal(report.budgetOperations,1);assert.equal(report.overdueEtas,1);assert.equal(report.actualExpenses,500);assert.equal(buildPortfolioReport([operation,budget],{...filters,phase:'approved'}).totalOperations,1);assert.ok(portfolioReportData('costs',report,filters,rates).sheets.some(s=>s.name==='Tributos calculados'));assert.ok(portfolioReportData('compliance',report,filters,rates).sheets.some(s=>s.name==='Pendências')); });
if(process.env.REPORT_QA==='1') { mkdirSync('output/currency-reports',{recursive:true}); const font=readFileSync('apps/web/public/fonts/NotoSansSC-Regular.ttf').toString('base64'); const pdf=await createOperationPdf(operation,context,font); writeFileSync('output/currency-reports/operation.pdf',Buffer.from(pdf.output('arraybuffer'))); const workbook=createOperationWorkbook(operation,context); await workbook.xlsx.writeFile('output/currency-reports/operation.xlsx'); writeFileSync('output/currency-reports/fixture.json',JSON.stringify({operation,rates,users:context.users})); console.log('QA exports',pdf.getNumberOfPages(),'pages'); }
