import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "./components/ui/table";
import { Button } from "./components/ui/button";
import { MoneyAmount, useCurrency } from "./components/money-amount";
import type { ReactNode } from "react";
import { DatePicker } from "./components/ui/date-picker";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BarChart3, Banknote, CheckCircle2, Download, ExternalLink, FileBarChart, FileText, MapPinned, ShipWheel, Users } from "lucide-react";
import { customsChannelMeta, importStatusMeta, type Customer, type ImportOperation } from "@exporta/domain";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./components/ui/select";
import { buildPortfolioReport, defaultPortfolioReportFilters, type PortfolioReportFilters, type PortfolioReportKey } from "./lib/portfolio-report";
import { useLocale } from "./lib/locale-context";

type MarketContext = { dollar: { sell: number; quotedAt: string; source: string }; updatedAt: string };
type Props = { operations: ImportOperation[]; customers: Customer[]; marketContext: MarketContext | null; onOpenOperation: (id: string) => void; onOpenOperations: () => void };
type ExportFormat = "pdf" | "xlsx" | null;
const reportMeta: Record<PortfolioReportKey, { title: string; description: string; icon: typeof BarChart3 }> = {
  executive: { title: "Visão executiva", description: "Custo, volume, risco e prioridades no mesmo recorte.", icon: BarChart3 },
  operations: { title: "Operação e riscos", description: "ETA, canais, pendências e pontos que pedem ação.", icon: AlertTriangle },
  costs: { title: "Custos e fechamento", description: "Composição projetada e concentração por NCM.", icon: Banknote },
  partners: { title: "Clientes e portos", description: "Concentração por cliente e porto.", icon: Users },
  compliance: { title: "Documentos e pendências", description: "Conformidade operacional por processo.", icon: FileText },
  market: { title: "Mercado e benchmark", description: "Câmbio, referências oficiais e categorias acompanhadas.", icon: MapPinned }
};
const reportKeys = Object.keys(reportMeta) as PortfolioReportKey[];
const safeKey = (value: string | null): PortfolioReportKey => reportKeys.includes(value as PortfolioReportKey) ? value as PortfolioReportKey : "executive";
const filterFromUrl = (): PortfolioReportFilters => { const fallback = defaultPortfolioReportFilters(); const params = new URLSearchParams(window.location.search); const status = params.get("status"); const channel = params.get("channel"); return { from: params.get("from") || fallback.from, to: params.get("to") || fallback.to, customer: params.get("customerId") || "all", port: params.get("port") || "all", status: status && status in importStatusMeta ? status as PortfolioReportFilters["status"] : "all", phase: params.get("phase") === "costs" ? "costs" : params.get("phase") === "approved" ? "approved" : "all", channel: channel && channel in customsChannelMeta ? channel as PortfolioReportFilters["channel"] : "all" }; };
const keyFromUrl = () => safeKey(new URLSearchParams(window.location.search).get("report"));
const reportUrl = (key: PortfolioReportKey, filters: PortfolioReportFilters) => { const params = new URLSearchParams({ report: key }); if (filters.from) params.set("from", filters.from); if (filters.to) params.set("to", filters.to); if (filters.customer !== "all") params.set("customerId", filters.customer); if (filters.port !== "all") params.set("port", filters.port); if (filters.status !== "all") params.set("status", filters.status); if (filters.phase && filters.phase !== "all") params.set("phase", filters.phase); if (filters.channel !== "all") params.set("channel", filters.channel); return `/relatorios?${params.toString()}`; };

export function ReportsView({ operations, customers, marketContext, onOpenOperation, onOpenOperations }: Props) {
  const [key, setKey] = useState<PortfolioReportKey>(keyFromUrl);
  const [filters, setFilters] = useState<PortfolioReportFilters>(filterFromUrl);
  const { rates, loading: currencyLoading } = useCurrency();
  const locale = useLocale();
  const phaseLabels = locale === "zh-CN" ? ["预算", "已批准", "已登记实际费用"] : locale === "en-US" ? ["Budgets", "Approved", "Recorded actual expenses"] : ["Custos", "Aprovado", "Despesas realizadas"];
  const [exportError, setExportError] = useState("");
  const [exporting, setExporting] = useState<ExportFormat>(null);
  const report = useMemo(() => buildPortfolioReport(operations, filters), [operations, filters]);
  const ports = useMemo(() => [...new Set(operations.map((operation) => operation.port).filter(Boolean))].sort((a, b) => a.localeCompare(b, "pt-BR")), [operations]);
  const update = (nextKey: PortfolioReportKey, nextFilters: PortfolioReportFilters) => { window.history.pushState({}, "", reportUrl(nextKey, nextFilters)); setKey(nextKey); setFilters(nextFilters); };
  useEffect(() => { const sync = () => { setKey(keyFromUrl()); setFilters(filterFromUrl()); }; window.addEventListener("popstate", sync); return () => window.removeEventListener("popstate", sync); }, []);
  const exportReport = async (format: Exclude<ExportFormat, null>) => { setExporting(format); setExportError(""); try { const { downloadPortfolioReportPdf, downloadPortfolioReportXlsx } = await import("./lib/portfolio-report-export"); if (format === "pdf") await downloadPortfolioReportPdf(key, report, { ...filters, customerLabel: customers.find((customer) => customer.id === filters.customer)?.tradeName || customers.find((customer) => customer.id === filters.customer)?.legalName }, rates); else await downloadPortfolioReportXlsx(key, report, { ...filters, customerLabel: customers.find((customer) => customer.id === filters.customer)?.tradeName || customers.find((customer) => customer.id === filters.customer)?.legalName }, rates); } catch (error) { setExportError(error instanceof Error ? error.message : "Não foi possível gerar o relatório."); } finally { window.setTimeout(() => setExporting(null), 350); } };
  const updateFilters = (changes: Partial<PortfolioReportFilters>) => update(key, { ...filters, ...changes });
  return <section className="page reports-page"><div className="page-heading reports-heading"><div><p className="eyebrow">INTELIGÊNCIA OPERACIONAL</p><h1>Relatórios</h1><p className="muted">Transforme a carteira de importações em decisões de custo, risco e prioridade.</p></div><div className="reports-heading__actions"><Button className="button button--secondary" onClick={() => exportReport("xlsx")} disabled={exporting !== null || currencyLoading}><Download size={17} /> {exporting === "xlsx" ? "Gerando XLSX…" : "Exportar XLSX"}</Button><Button className="button button--primary" onClick={() => exportReport("pdf")} disabled={exporting !== null || currencyLoading}><FileBarChart size={17} /> {exporting === "pdf" ? "Gerando PDF…" : "Exportar PDF"}</Button></div></div>
    {exportError && <p className="export-error" role="alert">{exportError}</p>}<nav className="report-templates" aria-label="Modelos de relatório">{reportKeys.map((item) => { const meta = reportMeta[item]; const Icon = meta.icon; return <Button key={item} className={key === item ? "is-active" : ""} onClick={() => update(item, filters)}><Icon size={17} /><span><strong>{meta.title}</strong><small>{meta.description}</small></span></Button>; })}</nav>
    <section className="panel reports-filters"><div><strong>Recorte do relatório</strong><small>Período e filtros ficam registrados na URL para compartilhar a mesma análise.</small></div><label className="field"><span>De</span><DatePicker label="De" value={filters.from} max={filters.to || undefined} onChange={(from) => updateFilters({ from })} /></label><label className="field"><span>Até</span><DatePicker label="Até" value={filters.to} min={filters.from || undefined} onChange={(to) => updateFilters({ to })} /></label><ReportSelect label="Cliente" value={filters.customer} onChange={(customer) => updateFilters({ customer })} options={[{ value: "all", label: "Todos os clientes" }, ...customers.map((customer) => ({ value: customer.id, label: customer.tradeName || customer.legalName }))]} /><ReportSelect label="Porto" value={filters.port} onChange={(port) => updateFilters({ port })} options={[{ value: "all", label: "Todos os portos" }, ...ports.map((port) => ({ value: port, label: port }))]} /><ReportSelect label="Fase" value={filters.phase ?? "all"} onChange={(phase) => updateFilters({ phase: phase as PortfolioReportFilters["phase"] })} options={[{ value: "all", label: "Todas as fases" }, { value: "costs", label: "Custos" }, { value: "approved", label: "Aprovado" }]} /><ReportSelect label="Status" value={filters.status} onChange={(status) => updateFilters({ status: status as PortfolioReportFilters["status"] })} options={[{ value: "all", label: "Todos os status" }, ...Object.entries(importStatusMeta).map(([value, meta]) => ({ value, label: meta.label }))]} /><Button className="text-button reports-filters__reset" type="button" onClick={() => update(key, defaultPortfolioReportFilters())}>Limpar filtros</Button></section>
    <ReportMetrics report={report} /><div className="report-phase-summary" data-localized><span>{report.budgetOperations} {phaseLabels[0]} <MoneyAmount value={report.budgetCost} /></span><span>{report.approvedOperations} {phaseLabels[1]} <MoneyAmount value={report.approvedCost} /></span><span>{phaseLabels[2]} <MoneyAmount value={report.actualExpenses} /></span></div>
    {key === "executive" && <ExecutiveReport report={report} onOpenOperation={onOpenOperation} onOpenOperations={onOpenOperations} />}
    {key === "operations" && <OperationsReport report={report} onOpenOperation={onOpenOperation} />}
    {key === "costs" && <CostsReport report={report} />}
    {key === "partners" && <PartnersReport report={report} />}
    {key === "compliance" && <ComplianceReport report={report} onOpenOperation={onOpenOperation} />}
    {key === "market" && <MarketReport report={report} marketContext={marketContext} />}
  </section>;
}
function ReportSelect({ label, value, options, onChange }: { label: string; value: string; options: { value: string; label: string }[]; onChange: (value: string) => void }) { return <label className="field report-select"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue /></SelectTrigger><SelectContent>{options.map((option) => <SelectItem value={option.value} key={option.value}>{option.label}</SelectItem>)}</SelectContent></Select></label>; }
function ReportMetrics({ report }: { report: ReturnType<typeof buildPortfolioReport> }) { return <div className="report-metrics"><ReportMetric label="Custo projetado" value={<MoneyAmount value={report.totalCost} />} detail={`${report.totalOperations} operações no recorte`} tone="blue" /><ReportMetric label="Risco de ETA" value={String(report.overdueEtas)} detail={`${report.nextSevenDays} nos próximos 7 dias`} tone={report.overdueEtas ? "red" : "green"} /><ReportMetric label="Pendências abertas" value={String(report.openTasks)} detail={`${report.pendingDocuments} documentos pendentes`} tone={report.openTasks ? "amber" : "green"} /><ReportMetric label="Custo médio" value={<MoneyAmount value={report.averageCost} />} detail={`${report.totalWeight.toLocaleString("pt-BR")} kg estimados`} tone="neutral" /></div>; }
function ReportMetric({ label, value, detail, tone }: { label: string; value: ReactNode; detail: string; tone: string }) { return <section className={`report-metric report-metric--${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></section>; }
function DistributionChart({ title, description, rows, valueFormat, empty = "Ainda não há dados para este recorte." }: { title: string; description: string; rows: { label: string; value: number }[]; valueFormat?: (value: number) => string; empty?: string }) { const max = Math.max(...rows.map((row) => row.value), 1); return <section className="panel report-chart"><div className="panel-header"><div><h2>{title}</h2><p>{description}</p></div></div>{rows.length ? <ol>{rows.slice(0, 8).map((row) => <li key={row.label}><div><span>{row.label}</span><strong>{valueFormat ? valueFormat(row.value) : <MoneyAmount value={row.value} />}</strong></div><i><b style={{ width: `${Math.max(4, row.value / max * 100)}%` }} /></i></li>)}</ol> : <p className="report-empty">{empty}</p>}</section>; }
function RiskTable({ report, onOpenOperation }: { report: ReturnType<typeof buildPortfolioReport>; onOpenOperation: (id: string) => void }) { return <section className="panel report-risk-table"><div className="panel-header"><div><h2>Prioridades operacionais</h2><p>Itens que precisam de acompanhamento no recorte selecionado.</p></div></div><div className="table-scroll"><Table><TableHeader><TableRow><TableHead>Prioridade</TableHead><TableHead>Operação</TableHead><TableHead>Cliente</TableHead><TableHead>Motivo</TableHead><TableHead>ETA</TableHead><TableHead><span className="sr-only">Abrir</span></TableHead></TableRow></TableHeader><TableBody>{report.risks.length ? report.risks.slice(0, 12).map((risk, index) => <TableRow key={`${risk.operation.id}-${risk.reason}-${index}`}><TableCell><span className={`report-priority report-priority--${risk.severity}`}>{risk.severity === "high" ? "Alta" : risk.severity === "medium" ? "Média" : "Baixa"}</span></TableCell><TableCell><strong>{risk.operation.reference}</strong></TableCell><TableCell>{risk.operation.customer}</TableCell><TableCell>{risk.reason}</TableCell><TableCell>{risk.operation.eta}</TableCell><TableCell><Button className="table-detail-button" onClick={() => onOpenOperation(risk.operation.id)}>Abrir</Button></TableCell></TableRow>) : <TableRow><TableCell className="empty-cell" colSpan={6}>Nenhuma prioridade encontrada neste recorte.</TableCell></TableRow>}</TableBody></Table></div></section>; }
const operationCount = (value: number) => `${value} ${value === 1 ? "operação" : "operações"}`;
function ExecutiveReport({ report, onOpenOperation, onOpenOperations }: { report: ReturnType<typeof buildPortfolioReport>; onOpenOperation: (id: string) => void; onOpenOperations: () => void }) { return <><div className="reports-grid"><DistributionChart title="Composição de custo" description="FOB, logística e tributos no valor projetado." rows={report.costRows} /><DistributionChart title="Carteira por etapa" description="Operações por status atual." rows={report.statusRows} valueFormat={operationCount} /></div><RiskTable report={report} onOpenOperation={onOpenOperation} /><div className="report-footer-action"><p>Precisa aprofundar uma operação específica?</p><Button className="button button--secondary" onClick={onOpenOperations}><ShipWheel size={17} /> Ver operações</Button></div></>; }
function OperationsReport({ report, onOpenOperation }: { report: ReturnType<typeof buildPortfolioReport>; onOpenOperation: (id: string) => void }) { return <><div className="reports-grid"><DistributionChart title="Canal aduaneiro" description="Distribuição atual por canal informado." rows={report.channelRows} valueFormat={operationCount} /><DistributionChart title="Etapa da operação" description="Carteira operacional no período." rows={report.statusRows} valueFormat={operationCount} /></div><RiskTable report={report} onOpenOperation={onOpenOperation} /></>; }
function CostsReport({ report }: { report: ReturnType<typeof buildPortfolioReport> }) { return <div className="reports-grid reports-grid--wide"><DistributionChart title="Composição de custo" description="Valores estimados na carteira selecionada." rows={report.costRows} /><DistributionChart title="NCMs com maior custo" description="Concentração estimada por classificação fiscal." rows={report.ncmRows} /></div>; }
function PartnersReport({ report }: { report: ReturnType<typeof buildPortfolioReport> }) { return <div className="reports-grid"><DistributionChart title="Clientes" description="Custo projetado por cliente." rows={report.customerRows} /><DistributionChart title="Portos" description="Custo projetado por porto de destino." rows={report.portRows} /></div>; }
function ComplianceReport({ report, onOpenOperation }: { report: ReturnType<typeof buildPortfolioReport>; onOpenOperation: (id: string) => void }) { const rows = report.risks.filter((risk) => /Documento|Pendência/.test(risk.reason)); return <><section className="panel report-compliance"><CheckCircle2 size={22} /><div><h2>Conformidade do recorte</h2><p><strong>{report.pendingDocuments}</strong> documentos pendentes ou vencidos e <strong>{report.openTasks}</strong> pendências abertas precisam de acompanhamento.</p></div></section><RiskTable report={{ ...report, risks: rows }} onOpenOperation={onOpenOperation} /></>; }
function MarketReport({ report, marketContext }: { report: ReturnType<typeof buildPortfolioReport>; marketContext: MarketContext | null }) { return <><section className="panel market-report-context"><div><p className="eyebrow">CONTEXTO EXTERNO</p><h2>Câmbio e referências oficiais</h2><p>O benchmark por NCM será habilitado quando a base mensal do Comex Stat estiver sincronizada. Até lá, a comparação externa não é inferida.</p></div><div className="market-report-context__quote"><span>USD PTAX</span><strong>{marketContext ? <MoneyAmount value={marketContext.dollar.sell} decimals={4} /> : "—"}</strong><small>{marketContext ? `Fonte: ${marketContext.dollar.source}` : "Cotação indisponível"}</small></div><div className="market-report-context__links"><a className="button button--secondary" href="https://comexstat.mdic.gov.br/pt/home" target="_blank" rel="noreferrer">Abrir Comex Stat <ExternalLink size={15} /></a><a className="text-button" href="https://www.gov.br/antaq/pt-br/central-de-conteudos/publicacoes-da-antaq/estatisticos-aquaviarios" target="_blank" rel="noreferrer">Estatístico ANTAQ <ExternalLink size={14} /></a></div></section><DistributionChart title="Categorias internas por NCM" description="Base para futura comparação com dados mensais do comércio exterior." rows={report.ncmRows} /></>; }
