import { useState } from "react";
import { z } from "zod";
import { cityFacilities, type PortCity, type PortCityExpense, type PortCitySettings, type PortFacility } from "@exporta/domain";
import { Button } from "./ui/button";
import { Form } from "./ui/form";
import { FormInput as Input } from "./ui/form-input";
import { NumberInput } from "./ui/number-input";
import { FieldSelect, SelectOption } from "./ui/field-select";
import { DialogRoot, DialogContent, DialogTitle, DialogClose } from "./ui/dialog";
import { MoneyAmount } from "./money-amount";
import { useLocale } from "../lib/locale-context";
import { translateUiText } from "../i18n";
import { Plus, Pencil, Trash2, X } from "lucide-react";
import type { FormSchema } from "../lib/form-schemas";
const schema = z.object({name:z.string().optional(),state:z.string().optional()}).catchall(z.string()).superRefine((values,context)=>{
  if (values.name !== undefined && !values.name.trim()) context.addIssue({code:"custom",path:["name"],message:"Preencha este campo."});
  if (values.state !== undefined && !/^[A-Z]{2}$/.test(values.state)) context.addIssue({code:"custom",path:["state"],message:"Preencha este campo."});
  for (const [key,value] of Object.entries(values)) {
    if (key.startsWith("label_") && !value?.trim()) context.addIssue({code:"custom",path:[key],message:"Preencha este campo."});
    if (key.startsWith("amount_") && (!value || !Number.isFinite(Number(value)) || Number(value)<0)) context.addIssue({code:"custom",path:[key],message:"Informe um número válido."});
  }
}) as FormSchema;
export function PortCitiesView({settings,loading,error,onSave,facilities,catalogState,onRetry}:{settings:PortCitySettings;loading:boolean;error:string;onSave:(next:PortCitySettings)=>Promise<void>;facilities:PortFacility[];catalogState:string;onRetry:()=>void}) {
 const locale=useLocale(),text=(value:string)=>translateUiText(locale,value);
 const [editing,setEditing]=useState<PortCity|null|"general"|undefined>(),[selected,setSelected]=useState<string>(""),[query,setQuery]=useState("");
 const city=settings.cities.find(city=>city.id===selected), terminals=city?cityFacilities(city,facilities):[];
 return <section className="page" data-localized><div className="page-heading"><div><h1>{text("Cidades portuárias")}</h1><p className="muted">{text("Configure cidades, terminais e despesas padrão para novos custos.")}</p></div><Button className="button button--primary" disabled={loading} onClick={()=>setEditing(null)}><Plus size={16}/>{text("Nova cidade")}</Button></div>
 {error&&<p className="field-error" role="alert">{error}</p>}
 <section className="panel"><div className="panel-header"><h2>{text("Despesas gerais de todos os portos")}</h2><Button className="button button--secondary" disabled={loading} onClick={()=>setEditing("general")}><Pencil size={16}/>{text("Editar despesas")}</Button></div><div className="port-default-list">{loading?<div className="skeleton skeleton--input"/>:settings.generalExpenses.length?settings.generalExpenses.map(expense=><div key={expense.id}><span>{expense.label}</span><MoneyAmount value={expense.amount}/></div>):<p className="muted">{text("Nenhuma despesa padrão cadastrada.")}</p>}</div></section>
 <section className="panel port-city-panel"><div className="panel-header"><h2>{text("Cidades cadastradas")}</h2><Input aria-label={text("Buscar cidade")} placeholder={text("Buscar cidade")} value={query} onChange={event=>setQuery(event.target.value)}/></div><div className="table-scroll"><table><thead><tr><th>{text("Cidade")}</th><th>UF</th><th>{text("Terminais ANTAQ")}</th><th>{text("Despesas padrão")}</th><th>{text("Ações")}</th></tr></thead><tbody>{loading?Array.from({length:3},(_,i)=><tr key={i}>{Array.from({length:5},(_,j)=><td key={j}><span className="skeleton skeleton--text"/></td>)}</tr>):settings.cities.filter(city=>`${city.name} ${city.state}`.toLowerCase().includes(query.toLowerCase())).map(city=><tr key={city.id}><td><Button className="text-button" onClick={()=>setSelected(city.id)}>{city.name}</Button></td><td>{city.state}</td><td>{catalogState==="ready"?cityFacilities(city,facilities).length:"—"}</td><td><MoneyAmount value={city.expenses.reduce((sum,item)=>sum+item.amount,0)}/></td><td><Button className="table-action" aria-label={`${text("Editar cidade")} ${city.name}`} onClick={()=>setEditing(city)}><Pencil size={16}/></Button></td></tr>)}</tbody></table></div>{!loading&&!settings.cities.length&&<p className="catalog-message">{text("Cadastre uma cidade para listar os terminais e configurar despesas.")}</p>}</section>
 {city&&<section className="panel port-city-panel"><div className="panel-header"><h2>{city.name} · {city.state}</h2><Button className="button button--secondary" onClick={()=>setEditing(city)}>{text("Editar cidade")}</Button></div><div className="port-default-list">{city.expenses.map(expense=><div key={expense.id}><span>{expense.label}</span><MoneyAmount value={expense.amount}/></div>)}</div>{catalogState==="error"?<Button className="button button--secondary" onClick={onRetry}>{text("Tentar novamente")}</Button>:catalogState!=="ready"?<div className="port-default-list"><span className="skeleton skeleton--input"/></div>:<div className="table-scroll"><table><thead><tr><th>{text("Terminal")}</th><th>{text("Tipo")}</th><th>{text("Situação")}</th></tr></thead><tbody>{terminals.map(terminal=><tr key={terminal.id}><td>{terminal.name}</td><td>{terminal.type}</td><td>{terminal.operationalStatus}</td></tr>)}{!terminals.length&&<tr><td colSpan={3}>{text("Nenhum terminal ANTAQ encontrado para esta cidade e UF.")}</td></tr>}</tbody></table></div>}</section>}
 {editing!==undefined&&<CityEditor city={editing==="general"?undefined:editing} expenses={editing==="general"?settings.generalExpenses:editing?.expenses??[]} onClose={()=>setEditing(undefined)} onSave={async (name,state,expenses)=>{const next=editing==="general"?{...settings,generalExpenses:expenses}:{...settings,cities:editing?settings.cities.map(city=>city.id===editing.id?{...city,name,state,expenses}:city):[...settings.cities,{id:crypto.randomUUID(),name,state,expenses}]};await onSave(next);setEditing(undefined);}}/>}</section>;
}
function CityEditor({city,expenses,onClose,onSave}:{city:PortCity|null|undefined;expenses:PortCityExpense[];onClose:()=>void;onSave:(name:string,state:string,expenses:PortCityExpense[])=>Promise<void>}){
 const locale=useLocale(),text=(value:string)=>translateUiText(locale,value),[rows,setRows]=useState(expenses),[saving,setSaving]=useState(false),[error,setError]=useState("");
 return <DialogRoot open onOpenChange={open=>{if(!open&&!saving)onClose();}}><DialogContent className="dialog--wide" aria-describedby={undefined} onInteractOutside={event=>event.preventDefault()}><header><DialogTitle>{text(city===undefined?"Despesas gerais":city?"Editar cidade":"Nova cidade")}</DialogTitle><DialogClose asChild><Button aria-label={text("Fechar")} disabled={saving}><X size={18}/></Button></DialogClose></header><Form schema={schema} className="form-grid" onSubmit={async values=>{setSaving(true);setError("");try{await onSave(values.name?.trim()??"",values.state??"",rows.map(row=>({id:row.id,label:values[`label_${row.id}`].trim(),amount:Number(values[`amount_${row.id}`])})));}catch(error){setError(error instanceof Error?error.message:text("Não foi possível salvar."));}finally{setSaving(false);}}}>
 {city!==undefined&&<><label className="field"><span>{text("Cidade")}</span><Input name="name" defaultValue={city?.name??""}/></label><label className="field"><span>UF</span><FieldSelect name="state" label="UF" defaultValue={city?.state??""}>{"AC AL AP AM BA CE DF ES GO MA MT MS MG PA PB PR PE PI RJ RN RS RO RR SC SP SE TO".split(" ").map(state=><SelectOption value={state} key={state}>{state}</SelectOption>)}</FieldSelect></label></>}
 <div className="full port-expense-editor">{rows.map(row=><div key={row.id}><label className="field"><span>{text("Descrição")}</span><Input name={`label_${row.id}`} defaultValue={row.label}/></label><label className="field"><span>{text("Valor")}</span><NumberInput aria-label={text("Valor")} currency="BRL" name={`amount_${row.id}`} defaultValue={row.amount}/></label><Button className="table-action" aria-label={text("Remover despesa")} disabled={saving} onClick={()=>setRows(rows.filter(item=>item.id!==row.id))}><Trash2 size={16}/></Button></div>)}</div>
 <Button className="button button--secondary full" disabled={saving} onClick={()=>setRows([...rows,{id:crypto.randomUUID(),label:"",amount:0}])}><Plus size={16}/>{text("Adicionar despesa")}</Button>{error&&<p className="field-error full" role="alert">{error}</p>}<Button type="submit" className="button button--primary form-submit" disabled={saving}>{text(saving?"Salvando…":"Salvar")}</Button></Form></DialogContent></DialogRoot>;
}
export function PortCityPicker({settings,onSelect,onBack}:{settings:PortCitySettings;onSelect:(id:string)=>void;onBack:()=>void}){
 const locale=useLocale(),text=(value:string)=>translateUiText(locale,value),[query,setQuery]=useState("");return <div className="customer-picker-dialog" data-localized><div className="customer-picker-dialog__toolbar"><Button onClick={onBack}>{text("Voltar")}</Button><Input aria-label={text("Buscar cidade")} placeholder={text("Buscar cidade")} value={query} onChange={event=>setQuery(event.target.value)}/></div><div className="customer-picker-dialog__list"><Button onClick={()=>onSelect("")}>{text("Cidade a definir")}</Button>{settings.cities.filter(city=>`${city.name} ${city.state}`.toLowerCase().includes(query.toLowerCase())).map(city=><Button key={city.id} onClick={()=>onSelect(city.id)}>{city.name} · {city.state}</Button>)}</div></div>;
}
