import { pricingBudget, calculateActualExpenses, calculateImport, effectiveTaxRate, effectiveOperationStatus, hasApprovedBudget, customsChannelMeta, importStatusMeta, portStatusMeta, shipmentStatusMeta, taxRateLabels, type ImportOperation, type OperationDocument, type OperationTask, type OperationTimelineEntry, type ImportExpense } from "@exporta/domain";
import { missingProductFields } from "./product-completeness";
import { createReportPdf, createReportWorkbook, downloadWorkbook, reportDate, type ReportData, type ReportSheet } from "./report-format";
import type { ExchangeRates } from "./currency";
export type ReportContext = { timeline: OperationTimelineEntry[]; tasks: OperationTask[]; documents: OperationDocument[]; rates?: ExchangeRates | null; users?: { id: string; name: string }[] };
const expenseStatus = { estimated: "Estimada", approved: "Aprovada", contracted: "Contratada", invoiced: "Faturada", paid: "Paga" };
const allocation = { fob: "FOB", weight: "Peso", volume: "Volume", quantity: "Quantidade", fixed: "Igual por item" };
const sourceLabel = { default: "Parametrização", ncm: "NCM", siscomex: "Siscomex", manual: "Manual" };
const filename = (reference: string, extension: string) => `relatorio-${reference.toLowerCase().replace(/[^a-z0-9]+/gi, "-")}.${extension}`;
export function operationReportData(operation: ImportOperation, context: ReportContext): ReportData {
  const calculated = calculateImport(operation), budget = pricingBudget(operation), actual = calculateActualExpenses(operation);
  const basis = budget?.priceBasis === "cif" ? "CIF" : "FOB";
  const name = (id?: string, fallback?: string) => context.users?.find((user) => user.id === id)?.name || fallback || "—";
  const moneyColumns = (indexes: number[]) => Object.fromEntries(indexes.map((index) => [index, "BRL" as const]));
  const expenseSheet = (title: string, expenses: ImportExpense[]): ReportSheet => ({ name: title, headers: ["Despesa / categoria", "Valor original", "Valor BRL", "Rateio / situação", "Fornecedor / documento", "Prazo / pagamento", "Observações"], moneyColumns: { 2: "BRL" }, rowMoneyColumns: expenses.map((expense) => ({ 1: expense.currency, 2: "BRL" })), widths: [35, 22, 22, 28, 35, 26, 45], rows: expenses.map((expense) => [`${expense.label} · ${expense.category}`, expense.amount, expense.currency === "USD" ? expense.amount * (expense.exchangeRate || calculated.exchangeRate) : expense.amount, `${allocation[expense.allocationMethod]} · ${expenseStatus[expense.status]}`, `${expense.vendor || "—"} / ${expense.document || "—"}`, `${reportDate(expense.dueDate)} / ${reportDate(expense.paidAt)}`, expense.notes || "—"]) });
  const estimated = budget.expenses;
  const taxes = (key: "ii" | "ipi" | "pis" | "cofins") => calculated.items.reduce((sum, item) => sum + item[key], 0);
  const sheets: ReportSheet[] = [
    { name: "Produtos", headers: ["Produto em português", "Original chinês", "Nome em inglês", "SKU / NCM", "Descrição de comércio exterior", "Quantidade", "Preço unitário USD", "Dados pendentes"], moneyColumns: { 6: "USD" }, widths: [35, 35, 32, 22, 55, 15, 24, 35], rows: operation.items.map((item) => [item.name, item.chineseName || "", item.englishName || "", `${item.sku || "—"} / ${item.ncm || "—"}`, item.description || "", item.quantity, item.unitPriceUsd, missingProductFields(item, estimated).join(", ") || "Completo"]) },
    { name: "Itens e custos", headers: ["Produto / NCM", "Base produtos BRL (FOB/CIF)", "Despesas rateadas", "Tributos", "Custo total", "Custo unitário"], moneyColumns: moneyColumns([1, 2, 3, 4, 5]), rows: calculated.items.map((item) => [`${item.name || item.chineseName || "Produto"} / ${item.ncm}`, item.itemFob, item.allocatedExpenses, item.taxes, item.totalCost, item.unitCost]) },
    { name: "Tributos calculados", headers: ["Produto / NCM", "II", "IPI", "PIS-importação", "COFINS-importação", "Total de tributos"], moneyColumns: moneyColumns([1, 2, 3, 4, 5]), rows: calculated.items.map((item) => [`${item.name || item.chineseName || "Produto"} / ${item.ncm}`, item.ii, item.ipi, item.pis, item.cofins, item.taxes]) },
    { name: "Volumes e embalagens", headers: ["Produto", "Compr. / larg. / alt. cm", "Unid. por caixa", "Caixas", "Peso por caixa kg", "Peso bruto total kg", "Peso líquido total kg", "Volume total m³"], rows: operation.items.map((item) => [item.name || item.chineseName || "—", `${item.lengthCm ?? "—"} / ${item.widthCm ?? "—"} / ${item.heightCm ?? "—"}`, item.unitsPerBox ?? null, item.boxCount ?? null, item.boxWeightKg ?? null, item.boxWeightKg && item.boxCount ? item.boxWeightKg * item.boxCount : item.grossWeightKg * item.quantity, item.netWeightKg ?? null, item.totalVolumeM3 ?? ((item.lengthCm || 0) * (item.widthCm || 0) * (item.heightCm || 0) * (item.boxCount || 0) / 1000000)]) },
    expenseSheet("Despesas estimadas", estimated), expenseSheet("Despesas realizadas", operation.actualExpenses ?? []),
    { name: "Premissas e alíquotas", headers: ["Escopo", "Tributo", "Alíquota %", "Origem", "Alterada manualmente", "Consultada / atualizada em", "Uso no cálculo"], rows: [
      ...(budget?.taxRates ?? []).map((tax) => ["Orçamento ativo", taxRateLabels[tax.code], tax.rate, sourceLabel[tax.source], tax.overridden ? "Sim" : "Não", reportDate(tax.updatedAt, true), !["icms_import", "siscomex", "afrmm"].includes(tax.code) ? "Aplicada conforme regra do item" : "Premissa; não compõe o total atual"]),
      ...operation.items.flatMap((item) => {
        const codes = [...new Set(["ii", "ipi", "pis_import", "cofins_import", "pis_sale", "cofins_sale", "ipi_sale", "icms_sale", "csll", "irpj", "irpj_additional", ...(item.taxRates ?? []).map((tax) => tax.code)])] as (keyof typeof taxRateLabels)[];
        return codes.map((code) => {
          const itemRate = item.taxRates?.find((tax) => tax.code === code);
          const legacy = code === "ii" ? item.iiRate : code === "ipi" ? item.ipiRate : 0;
          const budgetRate = budget?.taxRates.find((tax) => tax.code === code);
          const selected = itemRate ?? (legacy > 0 ? undefined : budgetRate);
          const value = effectiveTaxRate(item, budget, code);
          return [item.name || item.chineseName || item.id, taxRateLabels[code], value, selected ? sourceLabel[selected.source] : legacy > 0 ? "Legado; origem não registrada" : "Não informada", selected?.overridden ? "Sim" : "Não", reportDate(selected?.updatedAt, true), !["icms_import", "siscomex", "afrmm"].includes(code) ? "Alíquota efetiva aplicada no item" : "Premissa; não compõe o total atual"];
        });
      })
    ] },
    { name: "Versões de custos", headers: ["Versão", "Nome", "Situação", "Câmbio BRL por USD", "Acréscimo sobre custo %", "Criada em", "Aprovação / responsável", "Observações"], rows: (operation.budgets ?? []).map((version) => [version.number, version.name, version.status === "approved" ? "Aprovada" : version.status === "superseded" ? "Substituída" : "Rascunho", version.exchangeRate, version.marginRate, reportDate(version.createdAt, true), `${reportDate(version.approvedAt, true)} · ${name(version.approvedBy, version.approvedBy)}`, version.notes || "—"]) },
    { name: "Pendências", headers: ["Pendência", "Responsável", "Prazo", "Situação", "Criada em"], rows: context.tasks.map((task) => [task.title, name(task.assigneeId, task.assignee), reportDate(task.dueDate), task.completed ? "Concluída" : "Aberta", reportDate(task.createdAt, true)]) },
    { name: "Documentos", headers: ["Tipo / título", "Referência", "Emissão", "Validade", "Situação", "Registrado em"], rows: context.documents.map((document) => [`${document.type} · ${document.title}`, document.reference || "—", reportDate(document.issuedAt), reportDate(document.expiresAt), document.status === "expired" || (document.expiresAt && document.expiresAt < new Intl.DateTimeFormat("en-CA", { timeZone: "America/Sao_Paulo", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date())) ? "Vencido" : document.status === "available" ? "Disponível" : "Pendente", reportDate(document.createdAt, true)]) },
    { name: "Linha do tempo", headers: ["Marco", "Descrição", "Ocorreu em", "Registrado por", "Registrado em", "Tipo"], rows: [...context.timeline].sort((a, b) => a.occurredAt.localeCompare(b.occurredAt)).map((entry) => [entry.title, entry.description || "—", reportDate(entry.occurredAt, true), name(entry.actorId, entry.actorName), reportDate(entry.recordedAt ?? entry.occurredAt, true), entry.type === "status" ? "Status" : entry.type === "milestone" ? "Marco" : "Nota"]) }
  ];
  {
    const label = (item: typeof calculated.items[number]) => `${item.name || item.chineseName || "Produto"} / ${item.ncm}`;
    const amount = (item: typeof calculated.items[number], key: keyof NonNullable<typeof item.pricing>) => calculated.calculationReady ? item.pricing?.[key] ?? null : null;
    sheets.splice(3, 0,
      { name: "Bases e taxas por item", headers: ["Produto / NCM", "Peso líquido kg", "Base USD total", "Base convertida BRL", "CIF BRL", "Siscomex", "AFRMM", "Outras despesas"], moneyColumns: { 2: "USD", ...moneyColumns([3,4,5,6,7]) }, rows: calculated.items.map(item => [label(item), item.netWeightKg ?? null, item.pricing?.inputUsd ?? null, item.pricing?.inputBrl ?? null, item.pricing?.cifBrl ?? null, item.pricing?.siscomex ?? null, item.pricing?.afrmm ?? null, item.pricing?.otherExpenses ?? null]) },
      { name: "Venda por item", headers: ["Produto / NCM", "Custo total", "Acréscimo", "Venda total", "Venda unitária"], moneyColumns: moneyColumns([1,2,3,4]), rows: calculated.items.map(item => [label(item), item.totalCost, amount(item,"markup"), amount(item,"saleTotal"), amount(item,"saleUnit")]) },
      ...(["pis", "cofins", "ipi"] as const).map(code => ({ name: `${code.toUpperCase()} de saída`, headers: ["Produto / NCM", "Alíquota de saída %", "Débito na venda", "Crédito de entrada", "Saldo líquido"], moneyColumns: moneyColumns([2,3,4]), rows: calculated.items.map(item => [label(item), effectiveTaxRate(item,budget, `${code}_sale`), amount(item,`${code}Debit`), amount(item,`${code}Credit`), amount(item,`${code}Net`)]) })),
      { name: "Outros tributos de saída", headers: ["Produto / NCM", "ICMS", "CSLL", "IRPJ", "Adicional IRPJ", "Saída líquida total"], moneyColumns: moneyColumns([1,2,3,4,5]), rows: calculated.items.map(item => [label(item), amount(item,"icmsSale"), amount(item,"csll"), amount(item,"irpj"), amount(item,"irpjAdditional"), amount(item,"outputTaxes")]) }
    );
  }
  return { title: `${hasApprovedBudget(operation) ? "Custos aprovados" : "Orçamento de importação"} · ${operation.reference}`, rates: context.rates ?? null, metadata: [["Referência / cliente", `${operation.reference} · ${operation.customer}`], ["Fase / status", `${hasApprovedBudget(operation) ? "Aprovado" : "Custos"} · ${importStatusMeta[effectiveOperationStatus(operation)].label}`], ["Responsável / destino", `${name(operation.assigneeId, operation.assigneeName)} · ${operation.port || "Porto a definir"}`], ["Embarque / porto", `${shipmentStatusMeta[operation.shipmentStatus ?? "not_shipped"].label} · ${portStatusMeta[operation.portStatus].label}`], ["Contêiner / ETA / canal", `${operation.container || "—"} · ${reportDate(operation.eta)} · ${operation.customsChannel === "unassigned" ? "—" : customsChannelMeta[operation.customsChannel].label}`], ["Base / formação do preço", `${basis} · Acréscimo sobre custo`], ["Câmbio / acréscimo do orçamento", `${calculated.exchangeRate.toFixed(4)} BRL/USD · ${budget?.marginRate ?? 0}%`], ["Aprovação / atualização", `${reportDate(budget?.approvedAt, true)} · ${name(budget?.approvedBy, budget?.approvedBy)} / ${reportDate(operation.updatedAt, true)}`]], summary: [
      { label: `${basis} convertido`, value: calculated.fobBrl, currency: "BRL" }, { label: "Despesas estimadas", value: calculated.baseExpenses, currency: "BRL" },
      ...(["ii", "ipi", "pis", "cofins"] as const).map((key) => ({ label: { ii: "II", ipi: "IPI", pis: "PIS-importação", cofins: "COFINS-importação" }[key], value: taxes(key), currency: "BRL" as const })),
      { label: "Total de tributos", value: calculated.taxes, currency: "BRL" }, { label: "CUSTO TOTAL PROJETADO", value: calculated.totalCost, currency: "BRL" },
      ...(calculated.pricingTotals && calculated.calculationReady ? [{ label: "Acréscimo sobre custo", value: calculated.pricingTotals.markup, currency: "BRL" as const }, { label: "Tributos de saída líquidos", value: calculated.pricingTotals.outputTaxes, currency: "BRL" as const }, { label: "Custo + tributos de saída líquidos", value: calculated.pricingTotals.costWithOutputTaxes, currency: "BRL" as const }] : []),
      ...(calculated.suggestedSaleTotal === null ? [] : [{ label: "Venda sugerida pela margem", value: calculated.suggestedSaleTotal, currency: "BRL" as const }]), { label: "Despesas realizadas registradas", value: actual, currency: "BRL" }, { label: "Variação das despesas (realizado − estimado)", value: actual - calculated.baseExpenses, currency: "BRL" },
      { label: "Peso bruto / volume", value: calculated.totalWeight, unit: `kg · ${calculated.totalVolume} m³` }
    ], sheets, notes: [...calculated.calculationWarnings, ...["Modelo da planilha da empresa: base CIF para II e PIS/COFINS; IPI sobre CIF + II. Siscomex e AFRMM são valores monetários rateados por peso líquido. ICMS de importação não calculado.", "Venda = custo × (1 + acréscimo / 100). Saída líquida = débitos de PIS/COFINS/IPI menos os respectivos créditos de entrada + ICMS + CSLL + IRPJ + adicional. Créditos negativos são preservados.", "CSLL, IRPJ e adicional sobre o acréscimo reproduzem a referência operacional, não uma apuração fiscal. Revise o adicional de IRPJ da planilha (20%) com o contador.", "Custo + saída inclui a base dos produtos; não equivale ao valor E3 do FECHAMENTO, que reúne outros componentes e uma referência externa. Não representa caixa a pagar ao despachante."], "Despesas realizadas são lançamentos registrados, não o custo final completo da importação. A variação compara essas despesas com as despesas estimadas.", "As equivalências usam a mesma fotografia de cotações durante a exportação. Os valores são arredondados para exibição; o Excel mantém células numéricas e fórmulas de conversão.", "O relatório inclui todos os produtos, pendências, documentos e marcos, independentemente da paginação da tela."] };
}
export const createOperationWorkbook = (operation: ImportOperation, context: ReportContext) => createReportWorkbook(operationReportData(operation, context));
export const createOperationPdf = (operation: ImportOperation, context: ReportContext, fontBase64?: string) => createReportPdf(operationReportData(operation, context), fontBase64);
export async function downloadOperationXlsx(operation: ImportOperation, context: ReportContext) { await downloadWorkbook(createOperationWorkbook(operation, context), filename(operation.reference, "xlsx")); }
export async function downloadOperationPdf(operation: ImportOperation, context: ReportContext) { (await createOperationPdf(operation, context)).save(filename(operation.reference, "pdf")); }
