import { calculateImport, effectiveOperationStatus, hasApprovedBudget, importStatusMeta, customsChannelMeta, portStatusMeta, shipmentStatusMeta } from "@exporta/domain";
import type { PortfolioReport, PortfolioReportFilters, PortfolioReportKey } from "./portfolio-report";
import { operationReportData } from "./operation-report";
import { createReportPdf, createReportWorkbook, downloadWorkbook, reportDate, type ReportData, type ReportSheet } from "./report-format";
import type { ExchangeRates } from "./currency";
const reportTitle: Record<PortfolioReportKey, string> = { executive: "Visão executiva", operations: "Operação e riscos", costs: "Custos e fechamento", partners: "Clientes e portos", compliance: "Conformidade documental", market: "Mercado e benchmark" };
const filename = (key: PortfolioReportKey, extension: string) => `relatorio-${key}-${new Date().toISOString().slice(0, 10)}.${extension}`;
export function portfolioReportData(key: PortfolioReportKey, report: PortfolioReport, filters: PortfolioReportFilters, rates: ExchangeRates | null): ReportData {
  const operational: ReportSheet = { name: "Operações", headers: ["Referência / cliente", "Fase / status", "Responsável", "Porto / contêiner", "ETA / embarque", "Canal / status portuário", "Custo projetado"], moneyColumns: { 6: "BRL" }, rows: report.operations.map((operation) => [`${operation.reference} · ${operation.customer}`, `${hasApprovedBudget(operation) ? "Aprovado" : "Custos"} · ${importStatusMeta[effectiveOperationStatus(operation)].label}`, operation.assigneeName || "—", `${operation.port || "Porto a definir"} / ${operation.container || "—"}`, `${reportDate(operation.eta)} / ${shipmentStatusMeta[operation.shipmentStatus ?? "not_shipped"].label}`, `${operation.customsChannel === "unassigned" ? "—" : customsChannelMeta[operation.customsChannel].label} / ${portStatusMeta[operation.portStatus].label}`, calculateImport(operation).totalCost]) };
  const distribution = (name: string, rows: { label: string; value: number }[]): ReportSheet => ({ name, headers: [name, "Custo projetado BRL"], rows: rows.map((row) => [row.label, row.value]), moneyColumns: { 1: "BRL" } });
  const risks: ReportSheet = { name: "Prioridades", headers: ["Prioridade", "Operação", "Cliente", "Responsável", "Motivo", "ETA"], rows: report.risks.map((risk) => [{ high: "Alta", medium: "Média", low: "Baixa" }[risk.severity], risk.operation.reference, risk.operation.customer, risk.operation.assigneeName || "—", risk.reason, reportDate(risk.operation.eta)]) };
  const models = report.operations.map((operation) => ({ reference: operation.reference, data: operationReportData(operation, { timeline: operation.timeline ?? [], tasks: operation.tasks ?? [], documents: operation.documents ?? [], rates }) }));
  const combine = (name: string): ReportSheet => {
    const sample = models.map(model => model.data.sheets.find(sheet => sheet.name === name)).find(Boolean);
    // Stable column definitions also make empty portfolios useful to export.
    if (!sample) return { name, headers: ["Operação", "Registro"], rows: [] };
    return { name, headers: ["Operação", ...sample.headers], moneyColumns: sample.moneyColumns ? Object.fromEntries(Object.entries(sample.moneyColumns).map(([index, currency]) => [Number(index) + 1, currency])) : undefined, rowMoneyColumns: models.flatMap(({ data }) => { const section = data.sheets.find((sheet) => sheet.name === name); return (section?.rows ?? []).map((_, index) => Object.fromEntries(Object.entries(section?.rowMoneyColumns?.[index] ?? section?.moneyColumns ?? {}).map(([column, currency]) => [Number(column) + 1, currency]))); }), rows: models.flatMap(({ reference, data }) => (data.sheets.find((sheet) => sheet.name === name)?.rows ?? []).map((row) => [reference, ...row])) };
  };
  const financial = [distribution("Composição de custo", report.costRows), combine("Itens e custos"), combine("Tributos calculados"), combine("Despesas estimadas"), combine("Despesas realizadas"), combine("Premissas e alíquotas"), ...["Bases e taxas por item", "Venda por item", "PIS de saída", "COFINS de saída", "IPI de saída", "Outros tributos de saída"].map(combine)];
  const compliance = [combine("Pendências"), combine("Documentos"), combine("Linha do tempo")];
  const partners = [distribution("Clientes", report.customerRows), distribution("Portos", report.portRows)];
  const sheets = [operational, risks, ...(key === "costs" ? financial : key === "partners" ? partners : key === "compliance" ? compliance : key === "market" ? [distribution("NCMs", report.ncmRows)] : key === "operations" ? compliance : [financial[0], ...partners, ...compliance])];
  return { title: reportTitle[key], rates, metadata: [["Período", `${reportDate(filters.from)} a ${reportDate(filters.to)}`], ["Filtros", `Cliente: ${filters.customer === "all" ? "Todos" : filters.customerLabel || report.operations[0]?.customer || "Cliente selecionado"} · Porto: ${filters.port === "all" ? "Todos" : filters.port} · Fase: ${filters.phase === "approved" ? "Aprovado" : filters.phase === "costs" ? "Custos" : "Todas"}`], ["Status / canal", `${filters.status === "all" ? "Todos" : importStatusMeta[filters.status].label} · ${filters.channel === "all" ? "Todos" : customsChannelMeta[filters.channel].label}`]], summary: [
    { label: "Operações / custos / aprovadas", value: report.totalOperations, unit: `· ${report.budgetOperations} custos · ${report.approvedOperations} aprovadas` },
    { label: "Orçamentos em elaboração", value: report.budgetCost, currency: "BRL" }, { label: "Custos aprovados projetados", value: report.approvedCost, currency: "BRL" }, { label: "CUSTO TOTAL PROJETADO", value: report.totalCost, currency: "BRL" },
    { label: "Base dos produtos (FOB/CIF)", value: report.totalFob, currency: "BRL" }, { label: "Despesas estimadas", value: report.totalLogistics, currency: "BRL" }, { label: "Tributos calculados", value: report.totalTaxes, currency: "BRL" },
    { label: "Despesas realizadas registradas", value: report.actualExpenses, currency: "BRL" }, { label: "Variação de despesas", value: report.actualExpenses - report.totalLogistics, currency: "BRL" },
    { label: "Pendências abertas / documentos pendentes", value: report.openTasks, unit: `/ ${report.pendingDocuments}` }, { label: "ETA vencida / próximos 7 dias", value: report.overdueEtas, unit: `/ ${report.nextSevenDays}` }
  ], sheets, notes: ["O custo projetado utiliza o orçamento ativo: base dos produtos (FOB/CIF) + despesas estimadas + II + IPI + PIS + COFINS. Não representa receita ou custo realizado completo.", "Custos em elaboração e aprovados são apresentados separadamente. A previsão de chegada considera operações aprovadas que ainda não chegaram.", "Despesas realizadas representam os lançamentos registrados. A variação compara esse montante com as despesas estimadas.", "Todos os registros do recorte são exportados; paginação e limites de gráficos não excluem dados.", "O benchmark externo depende da sincronização Comex Stat; não são inferidos dados de mercado.", "As equivalências são indicativas e usam as cotações congeladas no momento da geração."] };
}
export const createPortfolioWorkbook = (key: PortfolioReportKey, report: PortfolioReport, filters: PortfolioReportFilters, rates: ExchangeRates | null) => createReportWorkbook(portfolioReportData(key, report, filters, rates));
export async function downloadPortfolioReportXlsx(key: PortfolioReportKey, report: PortfolioReport, filters: PortfolioReportFilters, rates: ExchangeRates | null) { await downloadWorkbook(createPortfolioWorkbook(key, report, filters, rates), filename(key, "xlsx")); }
export async function downloadPortfolioReportPdf(key: PortfolioReportKey, report: PortfolioReport, filters: PortfolioReportFilters, rates: ExchangeRates | null) { (await createReportPdf(portfolioReportData(key, report, filters, rates))).save(filename(key, "pdf")); }
